# Dockerfile to build aria2 Windows binary using ubuntu mingw-w64
# cross compiler chain.
#
# $ sudo docker build -t aria2-mingw - < Dockerfile.mingw
#
# After successful build, windows binary is located at
# /aria2/src/aria2c.exe.  You can copy the binary using following
# commands:
#
# $ sudo docker run --rm -it -v /path/to/dest:/out aria2-mingw cp /aria2/src/aria2c.exe /out

FROM ubuntu:22.04

LABEL original_maintainer="Tatsuhiro Tsujikawa"
LABEL maintainer="github.com/hiklah"

# Change HOST to i686-w64-mingw32 to build 32-bit binary
ARG HOST=x86_64-w64-mingw32

# Change ARIA2_VERSION to the version you want
ARG ARIA2_VERSION=1.37.0

# It would be better to use nearest ubuntu archive mirror for faster
# downloads.
# RUN sed -ie 's/archive\.ubuntu/jp.archive.ubuntu/g' /etc/apt/sources.list

RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y --no-install-recommends \
        make binutils autoconf automake autotools-dev libtool \
        patch ca-certificates \
        pkg-config git curl dpkg-dev gcc-mingw-w64 g++-mingw-w64 \
        autopoint libcppunit-dev libxml2-dev libgcrypt20-dev lzip \
        python3-docutils

RUN curl -L -O https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz && \
    curl -L -O https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-2.5.0.tar.bz2 && \
    curl -L -O https://www.sqlite.org/2023/sqlite-autoconf-3430100.tar.gz && \
    curl -L -O https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz && \
    curl -L -O https://github.com/c-ares/c-ares/releases/download/cares-1_19_1/c-ares-1.19.1.tar.gz && \
    curl -L -O https://libssh2.org/download/libssh2-1.11.0.tar.bz2 && \
    curl -L -O https://github.com/openssl/openssl/releases/download/OpenSSL_1_1_1w/openssl-1.1.1w.tar.gz

RUN tar xf gmp-6.3.0.tar.xz && \
    cd gmp-6.3.0 && \
    ./configure \
        --disable-shared \
        --enable-static \
        --prefix=/usr/local/$HOST \
        --host=$HOST \
        --disable-cxx \
        --enable-fat \
        CFLAGS="-mtune=generic -O2 -g0" && \
    make -j$(nproc) install

RUN tar xf expat-2.5.0.tar.bz2 && \
    cd expat-2.5.0 && \
    ./configure \
        --disable-shared \
        --enable-static \
        --prefix=/usr/local/$HOST \
        --host=$HOST \
        --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
    make -j$(nproc) install

RUN tar xf sqlite-autoconf-3430100.tar.gz && \
    cd sqlite-autoconf-3430100 && \
    ./configure \
        --disable-shared \
        --enable-static \
        --prefix=/usr/local/$HOST \
        --host=$HOST \
        --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
    make -j$(nproc) install

RUN tar xf zlib-1.3.1.tar.gz && \
    cd zlib-1.3.1 && \
    CC=$HOST-gcc \
    AR=$HOST-ar \
    RANLIB=$HOST-ranlib \
    STRIP=$HOST-strip \
    CFLAGS='-DZLIB_WINAPI' \
    ./configure \
        --prefix=/usr/local/$HOST \
        --static && \
    make -j$(nproc) install

RUN tar xf c-ares-1.19.1.tar.gz && \
    cd c-ares-1.19.1 && \
    ./configure \
        --disable-shared \
        --enable-static \
        --without-random \
        --prefix=/usr/local/$HOST \
        --host=$HOST \
        --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
        LIBS="-lws2_32" && \
    make -j$(nproc) install

RUN tar xf libssh2-1.11.0.tar.bz2 && \
    cd libssh2-1.11.0 && \
    ./configure \
        --disable-shared \
        --enable-static \
        --prefix=/usr/local/$HOST \
        --host=$HOST \
        --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
        LIBS="-lws2_32" && \
    make -j$(nproc) install

RUN tar xf openssl-1.1.1w.tar.gz && \
    cd openssl-1.1.1w && \
    ./Configure mingw64 no-shared no-tests \
        --prefix=/usr/local/$HOST \
        --cross-compile-prefix=$HOST- && \
    make -j$(nproc) && \
    make install

RUN curl -L -O https://github.com/aria2/aria2/releases/download/release-$ARIA2_VERSION/aria2-$ARIA2_VERSION.tar.xz && \
    tar xf aria2-$ARIA2_VERSION.tar.xz && mv aria2-$ARIA2_VERSION aria2 && cd aria2 && \
    sed -i "s/i686-w64-mingw32/x86_64-w64-mingw32/g" mingw-config && \
    sed -i "s|--without-openssl|--without-wintls --with-openssl --with-ca-bundle='C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt'|g" mingw-config && \
    autoreconf -i && ./mingw-config && make -j$(nproc) && \
    $HOST-strip src/aria2c.exe